"""Cascade foreign key constraints

Revision ID: 12af075a186
Revises: 296b8af182
Create Date: 2015-10-21 22:43:34.627676

"""

# revision identifiers, used by Alembic.
revision = '12af075a186'
down_revision = '296b8af182'
branch_labels = None
depends_on = None

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_user_link_ibfk_2', 'team_user_link', type_='foreignkey')
    op.drop_constraint('team_user_link_ibfk_1', 'team_user_link', type_='foreignkey')
    op.create_foreign_key(None, 'team_user_link', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'team_user_link', 'team', ['team_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_user_link', type_='foreignkey')
    op.drop_constraint(None, 'team_user_link', type_='foreignkey')
    op.create_foreign_key('team_user_link_ibfk_1', 'team_user_link', 'team', ['team_id'], ['id'])
    op.create_foreign_key('team_user_link_ibfk_2', 'team_user_link', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
