"""Team & User names must be unique

Revision ID: 1fffe5afa64
Revises: 12af075a186
Create Date: 2015-10-21 22:46:03.395355

"""

# revision identifiers, used by Alembic.
revision = '1fffe5afa64'
down_revision = '12af075a186'
branch_labels = None
depends_on = None

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'team', ['name'])
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'team', type_='unique')
    ### end Alembic commands ###
