"""Add created_at column

Revision ID: 2940488ae39
Revises: 2202b8ff11
Create Date: 2015-10-21 21:19:25.718827

"""

# revision identifiers, used by Alembic.
revision = '2940488ae39'
down_revision = '2202b8ff11'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('team_user_link', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_user_link', 'created_at')
    op.drop_column('team', 'created_at')
    ### end Alembic commands ###
