"""Add created_at for user

Revision ID: 296b8af182
Revises: 2d889f0751f
Create Date: 2015-10-21 22:35:28.619299

"""

# revision identifiers, used by Alembic.
revision = '296b8af182'
down_revision = '2d889f0751f'
branch_labels = None
depends_on = None

from alembic import op
import datetime
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at',
                                    sa.DateTime,
                                    default=datetime.datetime.utcnow,
                                    nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    ### end Alembic commands ###
